### ISSUE TITLE
Documentation now available online

### ISSUE THREAD

**Issue by fwitte** [oemof/tespy#3]
You can find the first version on [tespy.readthedocs.io](https://tespy.readthedocs.io).

**TODO**

- [x] documentation for the components characteristics is still missing.
- [x] update "Using TESPy" after renaming of some parameters.
- [x] add TESPy components part (similar to oemof/oemof-solph documentation)
- [x] fix broken links to equations of splitter, condenser, desuperheater and pipe in Using TESPy/TESPy Components.
- [x] adjust the docstrings for the component convergence checks
