### ISSUE TITLE
Roadmap to TESPy version 0.1.0

### ISSUE THREAD

**Issue by fwitte** [oemof/tespy#42]
TESPy version 0.1.0 will come in the near future, some milestones and features will have to be implemented on the way (also see #2).

- make network export and network reader handle compressor maps, see #46 
  - [x] add z1, z2 dimensions
  - [x] handle different characteristics by type of characteristics
  - [x] <del>add characteristics type field in char.csv</del>
- make components work with negative or zero mass flow
  - [x] negative massflow #43 
  - [x] <del>zero massflow (optional!)</del>
- write tests, test coverage > 75 %
  - [x] integrate examples with tests in docstrings (for class components and subsystems), see #45 
  - [x] write testfiles for other parts of code, see pr #52 
  - [x] benchmark cases.
- [x] test examples from examples repository, done, will upload with release!
- add log-file export, see #51 
  - [x] add logging support
  - [x] look for overlap with print_level
- fix issue #41 
  - [x] pre- and postprocessing for design and offdesign modes
- speed up calculation
  - [x] use CoolProp abstractstate instead of PropsSI interface
  - [x] <del>others?</del>
- [x] documentation revision, merge #45 
- [x] register a doi for TESPy

**Comment by fwitte** [comment]
Merged #54
